#!/bin/sh
#
# Usage: gnunet-logread-ipc | gnunet-logread
#
# ... obsoleted by gnunet-logread's new -f option that does the same thing

# FIXME: Replace /tmp with our use of $TMPDIR and similar.
ipc=${1:-/tmp/gnunet-logread-ipc.sock}
test -e "$ipc" || mkfifo "$ipc"
cat "$ipc"
