#!/bin/sh
# This file is in the public domain.
echo "Removing folder 'libltdl'..."
rm -rf libltdl

# This is more portable than `which' but comes with
# the caveat of not(?) properly working on busybox's ash:
existence()
{
    command -v "$1" >/dev/null 2>&1
}


if existence uncrustify; then
    echo "Installing uncrustify hook and configuration"
    # Install uncrustify format symlink (if possible)
    ln -s contrib/uncrustify.cfg uncrustify.cfg 2> /dev/null
    # Install pre-commit hook (if possible)
    ln -s ../../contrib/uncrustify_precommit .git/hooks/pre-commit 2> /dev/null
else
    echo "Uncrustify not detected, hook not installed. Please install uncrustify if you plan on doing development"
fi


# yapf can be a suffixed binary, don't change the essential logic
# of this if you change it.
if existence yapf || existence yapf3.0 || existence yapf3.1 || existence yapf3.2 || existence yapf3.3 || existence yapf3.4 || existence yapf3.5 || existence yapf3.6 || existence yapf3.7 || existence yapf3.8 || existence yapf3.9 || existence yapf4.0; then
    echo "Installing yapf symlink"
    # Install yapf style symlink (if possible)
    ln -s contrib/conf/.style.yapf 2> /dev/null
else
    echo "yapf not detected, please install yapf if you plan on contributing python code"
fi


echo "checking for libtoolize / libtool... "

if existence libtool || existence libtoolize || existence glibtoolize || existence slibtool; then
    autoreconf -if
    . "bin/pogen.sh"
else
    echo "*** No libtoolize (libtool) or libtool found, please install it ***" >&2;
    exit 1
fi
