#!/bin/sh
find src/ -name "*.c" -exec indent {} \;
find src/ -name "*.c" -exec indent {} \;
if test -x "`which 'dos2unix'`"
then
  find src/ -name "*.c" -exec dos2unix {} \;
  find src/ -name "*.c" -exec dos2unix {} \;
fi
