#!/bin/sh
# MAINDIR: Environment Variable for GNUnet workspace
# Note: The script will generate the grammar file C.out.jj under src/monkey
                                                                                                                                                                                    
rm -f *.java
mkdir -p org/gnunet/monkey/parser
cd org/gnunet/monkey/parser                                                                                                                                                                                 
jtb -printer -jd -np org.gnunet.monkey.parser.nodes -vp org.gnunet.monkey.parser.visitors -o $MAINDIR/src/monkey/C.out.jj $MAINDIR/src/monkey/C.jj                                              
javacc -STATIC=false $MAINDIR/src/monkey/C.out.jj

echo 'package org.gnunet.monkey.parser;' > PACKAGE
for n in *.java
do
 cat $n >> PACKAGE
 mv PACKAGE $n
 echo 'package org.gnunet.monkey.parser;' > PACKAGE
done

rm -f PACKAGE
                                                                                                                                