//
// Generated by JTB 1.3.2
//

package org.gnunet.seaspider.parser.nodes;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;TYPEDEF&gt;
 * f1 -> ( DataType() | FunctionType() )
 * f2 -> ";"
 * </PRE>
 */
public class TypeDeclaration implements Node {
   public NodeToken f0;
   public NodeChoice f1;
   public NodeToken f2;

   public TypeDeclaration(NodeToken n0, NodeChoice n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public TypeDeclaration(NodeChoice n0) {
      f0 = new NodeToken("typedef");
      f1 = n0;
      f2 = new NodeToken(";");
   }

   public void accept(org.gnunet.seaspider.parser.visitors.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.gnunet.seaspider.parser.visitors.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.gnunet.seaspider.parser.visitors.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.gnunet.seaspider.parser.visitors.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

