.TH GNUNET\-RESOLVER 1 "Jan 4, 2012" "GNUnet"

.SH NAME
gnunet\-resolver \- perform DNS resolution using GNUnet resolver service

.SH SYNOPSIS
.B gnunet\-resolver
.RI [ options ] HOSTNAME
.br

.SH DESCRIPTION
\fBgnunet\-resolver\fP can be used to lookup the IP address(es) for a hostname or the hostname for an IP address.  gnunet\-resolver uses the GNUnet service infrastructure to do this, but otherwise does nothing special.

.SH OPTIONS
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-r, \-\-reverse"
Perform a reverse lookup.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.


.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <bug\-gnunet@gnu.org>

.SH SEE ALSO
gnunet\-transport(1), nslookup(1)
