.TH GNUNET-NAT-AUTO 1 "January 6, 2017" "GNUnet"
.SH NAME
gnunet\-nat\-auto \- autoconfigure and test NAT traversal
.SH SYNOPSIS
.B gnunet\-nat\-auto
.RI [ options ]
.SH DESCRIPTION
This tool allows testing various NAT traversal functions, as well
as attempting auto\-configuration.
.SH OPTIONS
.IP "\-a,  \-\-auto"
Attempt auto\-configuration for NAT traversal.
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.IP "\-S NAME,  \-\-section=NAME"
Name of the configuration section with details about the configuration
to test. For example "transport-tcp".
.IP "\-t,  \-\-tcp"
Use TCP.
.IP "\-u,  \-\-udp"
Use UDP.
.IP "\-w,  \-\-write"
Write configuration to configuration file, useful in combination with
autoconfiguration (\-a).
.SH EXAMPLES
.PP
\fBAutomatic configuration:\fR
.TP
# gnunet\-nat\-auto \-aw
Probe and write result to configuration
.PP
\fBTest configuration:\fR
.TP
# gnunet\-nat\-auto -t \-S transport-tcp
Test TCP configuration
.TP
# gnunet\-nat\-auto -t \-S transport-http
Test HTTP configuration
.TP
# gnunet\-nat\-auto -u \-S transport-udp
Test UDP configuration
.SH BUGS
Report bugs by using Mantis <https://bugs.gnunet.org/> or by sending
electronic mail to <gnunet\-developers@gnu.org>
.SH SEE ALSO
gnunet\-transport(1) gnunet\-nat(1)
.PP
The full documentation for
.B gnunet
is maintained as a Texinfo manual.
If the
.B info
and
.B gnunet
programs are properly installed at your site, the command
.IP
.B info gnunet
.PP
should give you access to the complete handbook,
.IP
.B info gnunet-c-tutorial
.PP
will give you access to a tutorial for developers.
.PP
Depending on your installation, this information is also
available in
\fBgnunet\fP(7) and \fBgnunet-c-tutorial\fP(7).
