.TH GNUNET\-BCD 1 "December 5, 2013" "GNUnet"
.SH NAME
gnunet\-bcd \- run HTTP server to create GNS business cards
.SH SYNOPSIS
.B gnunet\-bcd
.RI [ options ]
.br
.SH DESCRIPTION
\fBgnunet\-bcd\fP can be used to create an business card with a QR code
containing the public key of a zone from the GNU Name System.
gnunet\-bcd requires LaTeX (pdflatex) with various packages to be
installed.  If it does not work for you, try installing the full
TeXLive distribution first, for example using the package\-manager
apt: "apt-get install texlive-full".
.SH OPTIONS
.B
.IP "\-p PORT, \-\-port=PORT"
Run the HTTP server on port PORT.
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.
.SH BUGS
Report bugs by using Mantis <https://bugs.gnunet.org/> or by sending
electronic mail to <gnunet\-developers@gnu.org>
.SH SEE ALSO
The full documentation for
.B gnunet
is maintained as a Texinfo manual.  If the
.B info
and
.B gnunet
programs are properly installed at your site, the command
.IP
.B info gnunet
.PP
should give you access to the complete handbook,
.IP
.B info gnunet-c-tutorial
.PP
will give you access to a tutorial for developers.
.PP
Depending on your installation, this information is also
available in
\fBgnunet\fP(7) and \fBgnunet-c-tutorial\fP(7).
