.TH GNUNET-TIMOUET 1 "June 5, 2018" "GNUnet"
.SH NAME
gnunet\-timeout \- run process with timeout
.SH SYNOPSIS
.B gnunet\-timeout
.RI TIMEOUT PROGRAM ARGS
.SH DESCRIPTION
\fBgnunet\-timeout\fP can be used to run another process with a
timeout.  Provided as the standard "timout" utility may not be
available on all platforms.
.SH BUGS
Report bugs by using Mantis <https://bugs.gnunet.org/> or by sending
electronic mail to <gnunet\-developers@gnu.org>
.SH SEE ALSO
timeout(1)
.PP
The full documentation for
.B gnunet
is maintained as a Texinfo manual.
If the
.B info
and
.B gnunet
programs are properly installed at your site, the command
.IP
.B info gnunet
.PP
should give you access to the complete handbook,
.IP
.B info gnunet-c-tutorial
.PP
will give you access to a tutorial for developers.
.PP
Depending on your installation, this information is also
available in
\fBgnunet\fP(7) and \fBgnunet-c-tutorial\fP(7).
