.TH GNUNET\-TIMOUET 1 "Jun 5, 2018" "GNUnet"

.SH NAME
gnunet\-timeout \- run process with timeout

.SH SYNOPSIS
.B gnunet\-timeout
.RI TIMEOUT PROGRAM ARGS
.br

.SH DESCRIPTION
\fBgnunet\-timeout\fP can be used to run another process with a
timeout.  Provided as the standard "timout" utility may not be
available on all platforms.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>

.SH SEE
timeout(1)
