.TH gnunet\-transport "1" "7 Nov 2014" "GNUnet"
.SH NAME
gnunet\-transport \- measure and control the transport subsystem

.SH SYNOPSIS
.B gnunet\-transport
[\fIOPTIONS\fR]
.SH DESCRIPTION
.PP

gnunet\-transport is a tool to access various functions of GNUnet's transport subsystem from the command\-line.  Most of these are not expected to be useful for end-users.  gnunet\-transport can be used to evaluate the performance of the transports, force a peer to connect to another peer (if possible).  Other functions should be added in the near future.

.TP
\fB\-b\fR, \fB\-\-benchmark\fR
measure how fast we are receiving data (from all connections).  On exit, the data rate will be reported.  Runs until aborted with CTRL-C.
.TP
\fB\-C \fIPEER\fR, \fB\-\-connect=PEER\fR
peer to connect to (used in conjunction with \-p)
.TP
\fB\-c \fIFILENAME\fR, \fB\-\-config=FILENAME\fR
configuration file to use
.TP
\fB\-e \fB\-\-events\fR
provide information about all connect and disconnect events (continuously)
.TP
\fB\-h\fR, \fB\-\-help\fR
print help page
.TP
\fB\-i\fR, \fB\-\-information\fR
print information about our current connections (once)
.TP
\fB\-L \fILOGLEVEL\fR, \fB\-\-loglevel=LOGLEVEL\fR
Change the loglevel.  Possible values for LOGLEVEL are ERROR, WARNING, INFO and DEBUG.
.TP
\fB\-l \fILOGFILE\fR, \fB\-\-logfile=LOGFILE\fR
configure logging to write logs to LOGFILE
.TP
\fB\-m\fR, \fB\-\-monitor\fR
print information about our current connections (continuously)
.TP
\fB\-p \fIPEER\fR, \fB\-\-peer=PEER\fR
the peer identity to connect to or monitor
.TP
\fB\-P, \fB\-\-plugins\fR
monitor session state of transport plugins
.TP
\fB\-s\fR, \fB\-\-send\fR
transmit (dummy) traffic as quickly as possible to the peer specified with the \-p option.  The rate will still be limited by the quota(s) determined by the peers (ATS subsystem).  Will run until CTRL\-C is pressed or until the connection to the other peer is disrupted.
.TP
\fB\-t\fR, \fB\-\-test\fR
test transport configuration.  With this flag, the tool will check if each of the configured transport plugins has a working address.  Plugins that do not have a listen port configured will be ignored.  The test is performed with the help of an external server (by default running on gnunet.org) which tries to contact the local machine.  The test can only work if the local GNUnet peer is not yet running.
.TP
\fB\-v\fR, \fB\-\-version\fR
print the version number
.TP
\fB\-V\fR, \fB\-\-verbose\fR
be verbose

.SH NOTES


.SH "REPORTING BUGS"
Report bugs by using mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
.SH "SEE ALSO"
\fBgnunet\-arm\fP(1)
