.TH GNUNET\-NAT\-AUTO 1 "6 Jan 2017" "GNUnet"

.SH NAME
gnunet\-nat\-auto \- autoconfigure and test NAT traversal

.SH SYNOPSIS
.B gnunet\-nat\-auto
.RI [ options ]
.br

.SH DESCRIPTION

This tool allows testing various NAT traversal functions, as well
as attempting auto\-configuration.

.SH OPTIONS
.B
.IP "\-a,  \-\-auto"
Attempt auto\-configuration for NAT traversal.

.B
.IP "\-b ADDRESS,  \-\-bind=ADDRESS"
Assume that the service is (locally) bound to ADDRESS.

.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.

.B
.IP "\-e ADDRESS,  \-\-external=ADDRESS"
Assume that ADDRESS is the globally visible address of the peer.

.IP "\-t,  \-\-tcp"
Use TCP.

.B
.IP "\-u,  \-\-udp"
Use UDP.

.B
.IP "\-w,  \-\-write"
Write configuration to configuration file, useful in combination with autoconfiguration (\-a).

.SH EXAMPLES
.PP

\fBAutomatic configuration:\fR

Probe and write result to configuration:

  # gnunet\-nat\-auto \-aw
  

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>

.SH SEE ALSO
gnunet\-transport(1) gnunet\-nat(1)

