.TH GNUNET\-MONKEY 1 "Jan 4, 2012" "GNUnet"

.SH NAME
gnunet\-monkey \- automatically debugging for services

.SH SYNOPSIS
.B gnunet-monkey
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-monkey\fP used to automatically debug a service.

.SH OPTIONS
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-m, \-\-mode"
Monkey's mode of operation: text: for writing debugging report in a text file, email: for sending debugging report to an email address.
.B
.IP "\-b, \-\-binary"
Path of the binary to debug with Monkey.
.B
.IP "\-o, \-\-output"
Only required in text mode: The path of the text file in which Monkey should write the debugging report.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.


.SH BUGS
Report bugs by using Mantis <https://gnunet.org/mantis/> or by sending electronic mail to <gnunet\-developers@gnu.org>

.SH SEE ALSO
gnunet\-service\-monkey(1)
