.\" This file is part of GNUnet.
.\" Copyright (C) 2001-2019 GNUnet e.V.
.\"
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3 or
.\" any later version published by the Free Software Foundation; with no
.\" Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
.\" copy of the license is included in the file
.\" ``FDL-1.3''.
.\"
.\" A copy of the license is also available from the Free Software
.\" Foundation Web site at @url{http://www.gnu.org/licenses/fdl.html}.
.\"
.\" Alternately, this document is also available under the General
.\" Public License, version 3 or later, as published by the Free Software
.\" Foundation.  A copy of the license is included in the file
.\" ``GPL3''.
.\"
.\" A copy of the license is also available from the Free Software
.\" Foundation Web site at @url{http://www.gnu.org/licenses/gpl.html}.
.\"
.\" SPDX-License-Identifier: GPL3.0-or-later OR FDL1.3-or-later
.\"
.Dd March 5, 2018
.Dt GNUNET-DNS2GNS 1
.Os
.Sh NAME
.Nm gnunet-dns2gns
.Nd
run a DNS-to-GNS proxy
.Sh SYNOPSIS
.Nm
.Op Fl c Ar FILENAME | Fl \-config= Ns Ar FILENAME
.Op Fl d Ar IP | Fl \-dns= Ns Ar IP
.Op Fl h | \-help
.Op Fl L Ar LOGLEVEL | Fl \-loglevel= Ns Ar LOGLEVEL
.Op Fl v | \-version
.Sh DESCRIPTION
.Nm
runs a DNS resolver which delegates requests GNS if the TLD matches one configured for GNS.
All other requests are forwarded to DNS.
This DNS proxy is useful for enabling non-personalized GNS\-resolution to an entire network or to offer GNS\-resolution to DNS users.
.Bl -tag -width Ds
.It Fl c Ar FILENAME | Fl \-config= Ns Ar FILENAME
Use the configuration file FILENAME.
.It Fl d Ar IP | Fl \-dns= Ns Ar IP
IP address of a recursive DNS resolver that should be used for non-GADS hostnames.
.It Fl h | \-help
Print short help on options.
.It Fl L Ar LOGLEVEL | Fl \-loglevel= Ns Ar LOGLEVEL
Use LOGLEVEL for logging.
Valid values are DEBUG, INFO, WARNING and ERROR.
.It Fl v | \-version
Print GNUnet version number.
.El
.Sh SEE ALSO
.Xr gnunet-gns-fcfs 1 ,
.Xr gnunet-gns 1 ,
.Xr gnunet-identity 1
.sp
The full documentation for gnunet is maintained as a Texinfo manual.
If the
.Xr info 1
and gnunet programs are properly installed at your site, the command
.Pp
.Dl info gnunet
.Pp
should give you access to the complete handbook,
.Pp
.Dl info gnunet-c-tutorial
.Pp
will give you access to a tutorial for developers.
.sp
Depending on your installation, this information is also available in
.Xr gnunet 7 and
.Xr gnunet-c-tutorial 7 .
.\".Sh HISTORY
.\".Sh AUTHORS
.Sh BUGS
Report bugs by using
.Lk https://bugs.gnunet.org
or by sending electronic mail to
.Aq Mt gnunet-developers@gnu.org .
