.TH GNUNET\-QR 1 "Sep 13, 2014" "GNUnet"

.SH NAME
gnunet\-qr \- Scan a QR code using a video device and import.

.SH SYNOPSIS
.B gnunet\-qr
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-qr\fP is a command line tool to scan a QR code using a video device and import.

.SH OPTIONS
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-d DEVICE,  \-\-device=DEVICE"
Use device DEVICE.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-s,  \-\-silent"
Do not show preview windows.
.B
.IP "\-v, \-\-verbose"
Be verbose.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
