.TH GNUNET\-MESH 1 "Jan 31, 2014" "GNUnet"

.SH NAME
gnunet\-mesh \- Print information about mesh tunnels and peers

.SH SYNOPSIS
.B gnunet\-mesh
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-mesh\fP prints information about mesh tunnels and peers.

.SH OPTIONS
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-l LOGFILE, \-\-logfile=LOGFILE"
Configure logging to write logs to LOGFILE.
.B
.IP "\-m, \-\-monitor"
Provide information about all tunnels (continuously) NOT IMPLEMENTED.
.B
.IP "\-t OWNER\_ID:TUNNEL\_ID, \-\-tunnel=OWNER\_ID:TUNNEL\_ID"
Provide information about a particular tunnel.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
