.\" This file is part of GNUnet.
.\" Copyright (C) 2001-2019 GNUnet e.V.
.\"
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3 or
.\" any later version published by the Free Software Foundation; with no
.\" Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
.\" copy of the license is included in the file
.\" FDL-1.3.
.\"
.\" A copy of the license is also available from the Free Software
.\" Foundation Web site at http://www.gnu.org/licenses/fdl.html}.
.\"
.\" Alternately, this document is also available under the General
.\" Public License, version 3 or later, as published by the Free Software
.\" Foundation.  A copy of the license is included in the file
.\" GPL3.
.\"
.\" A copy of the license is also available from the Free Software
.\" Foundation Web site at http://www.gnu.org/licenses/gpl.html
.\"
.\" SPDX-License-Identifier: GPL3.0-or-later OR FDL1.3-or-later
.\"
.Dd September 13, 2014
.Dt GNUNET-SCRYPT 1
.Os
.Sh NAME
.Nm gnunet-scrypt
.Nd manipulate GNUnet proof of work files
.Sh SYNOPSIS
.Nm
.Op Fl b Ar BITS | Fl -bits= Ns Ar BITS
.Op Fl c Ar FILENAME | Fl -config= Ns Ar FILENAME
.Op Fl h | -help
.Op Fl k Ar FILENAME | Fl -keyfile= Ns Ar FILENAME
.Op Fl L Ar LOGLEVEL | Fl -loglevel= Ns Ar LOGLEVEL
.Op Fl l Ar FILENAME | Fl -logfile= Ns Ar FILENAME
.Op Fl o Ar FILENAME | Fl -outfile= Ns Ar FILENAME
.Op Fl t Ar DELAY | Fl -timeout= Ns Ar DELAY
.Op Fl v | -version
.Sh DESCRIPTION
.Nm
is a command line tool to manipulate GNUnet proof of work files.
.Bl -tag -width indent
.It Fl b Ar BITS | Fl -bits= Ns Ar BITS
Number of bits to require for the proof of work.
.It Fl c Ar FILENAME | Fl -config= Ns Ar FILENAME
Use the configuration file
.Ar FILENAME .
.It Fl h | -help
Print short help on options.
.It Fl k Ar FILENAME | Fl -keyfile= Ns Ar FILENAME
Use
.Ar FILENAME
as the file with private key, otherwise the default
private key file is used.
.It Fl L Ar LOGLEVEL | Fl -loglevel= Ns Ar LOGLEVEL
Use LOGLEVEL for logging.
Valid values are DEBUG, INFO, WARNING and ERROR.
.It Fl l Ar FILENAME | Fl -logfile= Ns Ar FILENAME
Configure logging to write logs to FILENAME.
.It Fl o Ar FILENAME | Fl -outfile= Ns Ar FILENAME
File with proof of work, otherwise default is used.
.It Fl t Ar DELAY | Fl -timeout= Ns Ar DELAY
Time to wait between calculations.
.It Fl v | -version
Print GNUnet version number.
.Sh SEE ALSO
The full documentation for gnunet is maintained as a Texinfo manual.
If the
.Xr info 1
and gnunet programs are properly installed at your site, the command
.Pp
.Dl info gnunet
.Pp
should give you access to the complete handbook,
.Pp
.Dl info gnunet-c-tutorial
.Pp
will give you access to a tutorial for developers.
.Pp
Depending on your installation, this information is also available in
.Xr gnunet 7 and
.Xr gnunet-c-tutorial 7 .
.\".Sh HISTORY
.\".Sh AUTHORS
.Sh BUGS
Report bugs by using
.Lk https://bugs.gnunet.org
or by sending electronic mail to
.Aq Mt gnunet-developers@gnu.org .
