.TH GNUNET\-GNS 1 "Mar 5, 2012" "GNUnet"

.SH NAME
gnunet\-gns \- manipulate GNUnet GNS zones

.SH SYNOPSIS
.B gnunet\-gns
.RI [ options ] -z ZONEFILE
.br

.SH DESCRIPTION
\fBgnunet\-gns\fP can be used to create and manipulate a GNS zone.  

.SH OPTIONS
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-s NAME, \-\-shorten=NAME"
GNS domain name to shorten
.B
.IP "\-v, \-\-version"
Print GNUnet version number.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>


.SH "SEE ALSO"
\fBgnunet\-namestore\fP(1)
