.TH GNUNET\-RESOLVER 1 "Jan 4, 2012" "GNUnet"

.SH NAME
gnunet\-resolver \- build-in GNUnet stub resolver

.SH SYNOPSIS
.B gnunet\-resolver
.RI [ options ] [ hostname ]
.br

.SH DESCRIPTION
\fBgnunet\-resolver\fP uses build-in GNUnet stub resolver.

.SH OPTIONS
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and
ERROR.
.B
.IP "\-l LOGFILE, \-\-logfile=LOGFILE"
Configure logging to write logs to LOGFILE.
.B
.IP "\-r, \-\-reverse"
Perform a reverse lookup.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
