.Dd October 17, 2015
.Dt GNUNET-TRANSPORT 1
.Os
.Sh NAME
.Nm gnunet-transport
.Nd
measure and control the transport subsystem
.Sh SYNOPSIS
.Nm
.Op Fl b | \-benchmark
.Op Fl c Ar FILENAME | Fl \-config= Ns Ar FILENAME
.Op Fl D | \-disconnect
.Op Fl e | \-events
.Op Fl h | \-help
.Op Fl i | \-information
.Op Fl L Ar LOGLEVEL | Fl \-loglevel= Ns Ar LOGLEVEL
.Op Fl l Ar LOGFILE | Fl \-logfile= Ns Ar LOGFILE
.Op Fl m | \-monitor
.Op Fl p Ar PEER | Fl \-peer= Ns Ar PEER
.Op Fl P | \-plugins
.Op Fl s | \-send
.Op Fl v | \-version
.Op Fl V | \-verbose
.Sh DESCRIPTION
.Nm
is a tool to access various functions of GNUnet's transport subsystem from the command-line.
Most of these are not expected to be useful for end-users.
gnunet-transport can be used to evaluate the performance of the transports, force a peer to connect to another peer (if possible).
Other functions should be added in the near future.
.Bl -tag -width Ds
.It Fl b | \-benchmark
measure how fast we are receiving data (from all connections).
On exit, the data rate will be reported.
Runs until aborted with CTRL-C.
.It Fl c Ar FILENAME | Fl \-config= Ns Ar FILENAME
configuration file to use
.It Fl D | \-disconnect
force disconnection from a peer (used in conjunction with \-p).
Note that you can use the gnunet-ats command-line tool to suggest connects.
.It Fl e | \-events
provide information about all connect and disconnect events (continuously)
.It Fl h | \-help
print help page
.It Fl i | \-information
print information about our current connections (once)
.It Fl L Ar LOGLEVEL | Fl \-loglevel= Ns Ar LOGLEVEL
Change the loglevel.  Possible values for LOGLEVEL are ERROR, WARNING, INFO and DEBUG.
.It Fl l Ar LOGFILE | Fl \-logfile= Ns Ar LOGFILE
configure logging to write logs to LOGFILE
.It Fl m | \-monitor
print information about our current connections (continuously)
.It Fl p Ar PEER | Fl \-peer= Ns Ar PEER
the peer identity to connect to or monitor
.It Fl P | \-plugins
monitor session state of transport plugins
.It Fl s | \-send
transmit (dummy) traffic as quickly as possible to the peer specified
with the \-p option.  The rate will still be limited by the quota(s)
determined by the peers (ATS subsystem).  Will run until CTRL\-C is
pressed or until the connection to the other peer is disrupted.
.It Fl v | \-version
print the version number
.It Fl V | \-verbose
be verbose
.El
.Sh SEE ALSO
.Xr gnunet-arm 1 ,
.Xr gnunet-ats 1
.sp
The full documentation for gnunet is maintained as a Texinfo manual.
If the
.Xr info 1
and gnunet programs are properly installed at your site, the command
.Pp
.Dl info gnunet
.Pp
should give you access to the complete handbook,
.Pp
.Dl info gnunet-c-tutorial
.Pp
will give you access to a tutorial for developers.
.sp
Depending on your installation, this information is also available in
.Xr gnunet 7 and
.Xr gnunet-c-tutorial 7 .
.\".Sh HISTORY
.\".Sh AUTHORS
.Sh BUGS
Report bugs by using
.Lk https://bugs.gnunet.org
or by sending electronic mail to
.Aq Mt gnunet-developers@gnu.org .
