.TH GNUNET\-ECC 1 "June 5, 2017" "GNUnet"

.SH NAME
gnunet\-ecc \- manipulate GNUnet ECC key files

.SH SYNOPSIS
.B gnunet\-ecc
.RI [ options ] FILENAME
.br

.SH DESCRIPTION
\fBgnunet\-ecc\fP can be used to create an ECC private key and to
print the corresponding public key.  You must specify a filename
containing an ECC private key in GNUnet format as an argument.  If the
file does not exist, gnunet\-ecc will create a key.  This may then
take a while.  If the option \-p is given, the corresponding public
key will be printed to the console.

.SH OPTIONS
.IP "\-g COUNT, \-\-generate-keys=COUNT"
Create COUNT public-private key pairs and write them to FILENAME.
Used for creating a file for testing.
.IP "\-p, \-\-print-public-key"
Print the corresponding public key to stdout.  This is the value used
for PKEY records in GNS.
.IP "\-P, \-\-print-private-key"
Print the corresponding private key to stdout.  This is the value used
for PKEY records in GNS.
.IP "\-x, \-\-print-hex"
Print the corresponding public key to stdout in HEX format.  Useful
for comparing to Ed25519 keys in X.509 tools.
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.IP "\-h, \-\-help"
Print short help on options.
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and
ERROR.
.IP "\-v, \-\-version"
Print GNUnet version number.


.SH BUGS
Report bugs by using Mantis <https://bugs.gnunet.org/> or by sending
electronic mail to <gnunet\-developers@gnu.org>
.SH SEE ALSO
The full documentation for
.B gnunet
is maintained as a Texinfo manual.  If the
.B info
and
.B gnunet
programs are properly installed at your site, the command
.IP
.B info gnunet
.PP
should give you access to the complete handbook,
.IP
.B info gnunet-c-tutorial
.PP
will give you access to a tutorial for developers.
.PP
Depending on your installation, this information is also
available in
\fBgnunet\fP(7) and \fBgnunet-c-tutorial\fP(7).
