.TH GNUNET\-GNS\-IMPORT 1 "Jan 31, 2014" "GNUnet"

.SH NAME
gnunet\-gns\-import \- import some GNS authorities into your GNS namestore

.SH SYNOPSIS
.B gnunet\-gns\-import
.br

.SH DESCRIPTION
\fBgnunet\-gns\-import\fP calls gnunet-namestore to fetch some GNS authorities into your GNS namestore.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>

.SH SEE ALSO
gnunet\-gns(1), gnunet\-namestore(1)
