.TH GNUNET\-TRANSPORT\-CERTIFICATE\-CREATION 1 "Jan 31, 2014" "GNUnet"

.SH NAME
gnunet\-transport\-certificate\-creation \- create certificate for HTTPS transport

.SH SYNOPSIS
.B gnunet\-transport\-certificate\-creation
.I privatekey certificate
.br

.SH DESCRIPTION
\fBgnunet\-transport\-certificate\-creation\fP uses openssl to generate a RSA
private key and then a self-signed certificate for HTTPS transport.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>

.SH SEE ALSO
gnunet\-transport(1)
