.TH GNUNET\-SCRYPT 1 "Sep 13, 2014" "GNUnet"

.SH NAME
gnunet\-scrypt \- Manipulate GNUnet proof of work files.

.SH SYNOPSIS
.B gnunet\-scrypt
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-scrypt\fP is a command line tool to manipulate GNUnet proof of work files.

.SH OPTIONS
.B
.IP "\-b BITS,  \-\-bits=BITS"
Number of bits to require for the proof of work.
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-k FILE, \-\-keyfile=FILE"
File with private key, otherwise default is used.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-l LOGFILE, \-\-logfile=LOGFILE"
Configure logging to write logs to LOGFILE.
.B
.IP "\-o FILE, \-\-outfile=FILE"
File with proof of work, otherwise default is used.
.B
.IP "\-t TIME, \-\-timeout=TIME"
Time to wait between calculations.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
