.\" This file is part of GNUnet.
.\" Copyright (C) 2001-2019 GNUnet e.V.
.\"
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3 or
.\" any later version published by the Free Software Foundation; with no
.\" Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
.\" copy of the license is included in the file
.\" FDL-1.3.
.\"
.\" A copy of the license is also available from the Free Software
.\" Foundation Web site at http://www.gnu.org/licenses/fdl.html}.
.\"
.\" Alternately, this document is also available under the General
.\" Public License, version 3 or later, as published by the Free Software
.\" Foundation.  A copy of the license is included in the file
.\" GPL3.
.\"
.\" A copy of the license is also available from the Free Software
.\" Foundation Web site at http://www.gnu.org/licenses/gpl.html
.\"
.\" SPDX-License-Identifier: GPL3.0-or-later OR FDL1.3-or-later
.\"
.Dd November 2, 2011
.Dt GNUNET-FS 1
.Os
.Sh NAME
.Nm gnunet-fs
.Nd measure and control the FS subsystem
.Sh SYNOPSIS
.Nm
.Op Fl c Ar FILENAME | Fl \-config= Ns Ar FILENAME
.Op Fl h | \-help
.Op Fl i | \-list-indexed
.Op Fl L Ar LOGLEVEL | Fl \-loglevel= Ns Ar LOGLEVEL
.Op Fl v | \-version
.Op Fl V | \-verbose
.Sh DESCRIPTION
.Nm
is a tool to access various functions of GNUnet's FS subsystem
from the command-line.
Most of these are not expected to be useful for end-users.
gnunet-fs can currently only be used to obtain a list of indexed files.
Other functions should be added in the near future.
.Bl -tag -width indent
.It Fl c Ar FILENAME | Fl \-config= Ns Ar FILENAME
Configuration file to use.
.It Fl h | \-help
Print the help page.
.It Fl i | \-list-indexed
Print information about files that are currently indexed by file-sharing.
.It Fl L Ar LOGLEVEL | Fl \-loglevel= Ns Ar LOGLEVEL
Change the loglevel.
Possible values for LOGLEVEL are ERROR, WARNING, INFO and DEBUG.
.It Fl v | \-version
Print the version number.
.It Fl V | \-verbose
Be verbose.
.El
.Sh SEE ALSO
.Xr gnunet-publish 1
.Pp
The full documentation for gnunet is maintained as a Texinfo manual.
If the
.Xr info 1
and gnunet programs are properly installed at your site, the command
.Pp
.Dl info gnunet
.Pp
should give you access to the complete handbook,
.Pp
.Dl info gnunet-c-tutorial
.Pp
will give you access to a tutorial for developers.
.Pp
Depending on your installation, this information is also available in
.Xr gnunet 7 and
.Xr gnunet-c-tutorial 7 .
.\".Sh HISTORY
.\".Sh AUTHORS
.Sh BUGS
Report bugs by using
.Lk https://bugs.gnunet.org
or by sending electronic mail to
.Aq Mt gnunet-developers@gnu.org .
