.TH GNUNET-CONFIG 1 "July 15, 2012" "GNUnet"
.SH NAME
gnunet\-config \- manipulate GNUnet configuration files
.SH SYNOPSIS
.B gnunet\-config
.RI [ options ]
.SH DESCRIPTION
\fBgnunet\-config\fP can be used to read or modify GNUnet configuration files.
.SH OPTIONS
.IP "\-f, \-\-filename"
Try to perform expansions as if the option values represent filenames (will
also be applied even if the option is not really a filename).
.IP "\-s SECTION, \-\-section=SECTION"
Which configuration section should be accessed or edited. Required option.
.IP "\-S, \-\-list\-sections"
List available configuration sections for use with \-\-section.
.IP "\-W, \-\-rewrite"
Consider differences to defaults only.
.IP "\-o OPTION, \-\-option=OPTION"
Which configuration option should be accessed or edited.  Required to set a value.
If not given, all values of a given section will be printed in the
format "OPTION = VALUE".
.IP "\-V VALUE, \-\-value VALUE"
Configuration value to store in the given section under the given option.
Must only be given together with \-s and \-o options.
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.IP "\-h, \-\-help"
Print short help on options.
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.IP "\-v, \-\-version"
Print GNUnet version number.
.SH BUGS
Report bugs by using Mantis <https://bugs.gnunet.org/> or by sending
electronic mail to <gnunet\-developers@gnu.org>
.SH SEE ALSO
The full documentation for
.B gnunet
is maintained as a Texinfo manual.
If the
.B info
and
.B gnunet
programs are properly installed at your site, the command
.IP
.B info gnunet
.PP
should give you access to the complete handbook,
.IP
.B info gnunet-c-tutorial
.PP
will give you access to a tutorial for developers.
.PP
Depending on your installation, this information is also
available in
\fBgnunet\fP(7) and \fBgnunet-c-tutorial\fP(7).
