.Dd January 31, 2014
.Dt GNUNET-TRANSPORT-CERTIFICATE-CREATION 1
.Os
.Sh NAME
.Nm gnunet-transport-certificate-creation
.Nd
create certificate for HTTPS transport
.Sh SYNOPSIS
.Nm
.Op privatekey
.Op certificate
.Sh DESCRIPTION
.Nm
uses openssl to generate a RSA private key and then a self-signed certificate for HTTPS transport.
.Sh SEE ALSO
.Xr gnunet-transport 1
.sp
The full documentation for gnunet is maintained as a Texinfo manual.
If the
.Xr info 1
and gnunet programs are properly installed at your site, the command
.Pp
.Dl info gnunet
.Pp
should give you access to the complete handbook,
.Pp
.Dl info gnunet-c-tutorial
.Pp
will give you access to a tutorial for developers.
.sp
Depending on your installation, this information is also available in
.Xr gnunet 7 and
.Xr gnunet-c-tutorial 7 .
.\".Sh HISTORY
.\".Sh AUTHORS
.Sh BUGS
Report bugs by using
.Lk https://bugs.gnunet.org
or by sending electronic mail to
.Aq Mt gnunet-developers@gnu.org .
