.TH GNUNET\-TESTING 1 "January 4, 2012" "GNUnet"
.SH NAME
gnunet\-testing \- Command line tool to access the testing library.
.SH SYNOPSIS
.B gnunet\-testing
.RI [ options ]
.br
.SH DESCRIPTION
\fBgnunet\-testing\fP is a command line tool to access the testing
library.
.SH OPTIONS
.IP "\-C,  \-\-cfg"
Create unique configuration files.
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.IP "\-H, \-\-hostkeys"
Host key file.
.IP "\-h, \-\-help"
Print short help on options.
.IP "\-k, \-\-key"
Create hostkey files from pre-computed hostkey list.
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.IP "\-l LOGFILE, \-\-logfile=LOGFILE"
Configure logging to write logs to LOGFILE.
.IP "\-n, \-\-number"
Number of unique configuration files or hostkeys to create.
.IP "\-t, \-\-template"
Configuration template.
.IP "\-v, \-\-version"
Print GNUnet version number.
.SH BUGS
Report bugs by using Mantis <https://bugs.gnunet.org/> or by sending
electronic mail to <gnunet\-developers@gnu.org>
.SH SEE ALSO
The full documentation for
.B gnunet
is maintained as a Texinfo manual.
If the
.B info
and
.B gnunet
programs are properly installed at your site, the command
.IP
.B info gnunet
.PP
should give you access to the complete handbook,
.IP
.B info gnunet-c-tutorial
.PP
will give you access to a tutorial for developers.
.PP
Depending on your installation, this information is also
available in
\fBgnunet\fP(7) and \fBgnunet-c-tutorial\fP(7).
