.Dd March 6, 2019
.Dt GNUNET-GNS-PROXY-SETUP-CA 1
.Os
.Sh NAME
.Nm gnunet-gns-proxy-setup-ca
.Nd generate an X509 certificate for gnunet-gns-proxy and install it
.Sh SYNOPSIS
.Nm
.Op Fl c Ar FILE
.\".Op Fl f Ar FILE
.Op Fl h
.Op Fl v
.Op Fl V
.Sh DESCRIPTION
.Nm
is a shell script to generate X509 certificates for your gnunet-gns-proxy and to install it for both GNUnet and your web browser.
It currently supports Firefox and Chrome based browsers through the help of external helpers: certutil (nss) is used for the  import into webbrowsers, openssl is used to generated the CA.
.Bl -tag -width Ds
.It Fl c Ar FILE
Use the configuration file FILE.
.\" .It Fl f
.\" Perform expansions of the variables used in the config value of gns-proxy.
.\" This will usually expand $GNUNET_DATA_HOME to represents its path.
.It Fl h
Print short help on options
.It Fl v
Print the version
.It Fl V
be verbose
.El
.Sh FILES
.Pa gnunet.conf
.Sh SEE ALSO
.Xr gnunet-gns 1 ,
.Xr gnunet-gns-proxy 1 ,
.Xr gnunet.conf 5
.sp
The full documentation for gnunet is maintained as a Texinfo manual.
If the
.Xr info 1
and gnunet programs are properly installed at your site, the command
.Bd -literal -offset indent -compact
        info gnunet
.Ed
should give you access to the complete handbook,
.Bd -literal -offset indent -compact
        info gnunet-c-tutorial
.Ed
will give you access to a tutorial for developers.
.sp
Depending on your installation, this information is also
available in
.Xr gnunet 7 and
.Xr gnunet-c-tutorial 7 .
.Sh HISTORY
This man page first appeared in GNUnet 0.11.1.
.Sh AUTHORS
This page was written by
.An ng0 Aq Mt ng0@gnunet.org .
.Sh BUGS
Report bugs by using
.Lk https://bugs.gnunet.org
or by sending electronic mail to
.Aq Mt bug-gnunet@gnu.org .
