.TH gnunet\-core "1" "11 Apr 2014" "GNUnet"
.SH NAME
gnunet\-core \- monitor CORE subsystem

.SH SYNOPSIS
.B gnunet\-core
[\fIOPTIONS\fR]
.SH DESCRIPTION
.PP

gnunet\-core is a tool to access various functions of GNUnet's core subsystem from the command\-line.  The only function right now is to monitor the status of peers known to the CORE service.

.TP
\fB\-c \fIFILENAME\fR, \fB\-\-config=FILENAME\fR
configuration file to use
.TP
\fB\-h\fR, \fB\-\-help\fR
print help page
.TP
\fB\-L \fILOGLEVEL\fR, \fB\-\-loglevel=LOGLEVEL\fR
Change the loglevel.  Possible values for LOGLEVEL are ERROR, WARNING, INFO and DEBUG.
.TP
\fB\-m\fR, \fB\-\-monitor\fR
in monitor mode, gnunet\-core will continuously print the connection status, instead of giving just a snapshot
.TP
\fB\-v\fR, \fB\-\-version\fR
print the version number
.TP
\fB\-V\fR, \fB\-\-verbose\fR
be verbose

.SH NOTES


.SH "REPORTING BUGS"
Report bugs by using mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
.SH "SEE ALSO"
\fBgnunet\-transport\fP(1)
