.TH GNUNET\-TESTING 1 "Jan 4, 2012" "GNUnet"

.SH NAME
gnunet\-testing \- Command line tool to access the testing library.

.SH SYNOPSIS
.B gnunet\-testing
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-testing\fP is a command line tool to access the testing library.

.SH OPTIONS
.B
.IP "\-C,  \-\-cfg"
Create unique configuration files.
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-H, \-\-hostkeys"
Host key file.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-k, \-\-key"
Create hostkey files from pre-computed hostkey list.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-l LOGFILE, \-\-logfile=LOGFILE"
Configure logging to write logs to LOGFILE.
.B
.IP "\-n, \-\-number"
Number of unique configuration files or hostkeys to create.
.B
.IP "\-t, \-\-template"
Configuration template.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
