.TH GNUNET-IDENTITY "1" "16 Jul 2013" "GNUnet"
.SH NAME
gnunet\-identity \- create, delete or list egos
.SH SYNOPSIS
.B gnunet\-identity
[options]
.SH DESCRIPTION
.PP
gnunet\-identity is a tool for managing egos.  An ego is the persona that controls a namespace.  It is identical to a public\-private ECC key pair.

gnunet\-identity can be used to list all of the egos that were created locally, to create new egos, and to delete existing egos (the namespace will continue to exist, but it will be impossible to add additional data to it).

Creating a new ego requires using the \-C option together with an identifier (name) that is to be used for the new ego.  This identifier is only used locally for this peer and not shared with other peers.

.TP
\fB\-C NAME\fR, \fB\-\-create=NAME\fR
Creates a new ego with the given NAME.

.TP
\fB\-D NAME\fR, \fB\-\-delete=NAME\fR
Delete the ego with the given NAME.

.TP
\fB\-e NAME\fR, \fB\-\-ego=NAME\fR
Perform "set" operation with the respective ego.  Needs to be used together with option \-s.

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help page.

.TP
\fB\-d\fR, \fB\-\-display\fR
display all ouf our egos

.TP
\fB\-m\fR, \fB\-\-monitor\fR
run in monitor mode, listing all ouf our egos until CTRL-C is pressed. Each ego is listed together with a unique pointer value; if egos are renamed, that pointer value remains the same; if egos are deleted, they are listed one more time with a name of "<null>".

.TP
\fB\-s SUBSYSTEM\fR, \fB\-\-set=SUBSYSTEM\fR
Perform "set" operation for the specified SUBSYSTEM with the respective ego.  Needs to be used together with option \-e.  After this, the given SUBSYSTEM will use the ego with the specified NAME.  This will fail if NAME does not yet exist.


.SH FILES
.TP
~/.gnunet/egos/
Directory where the egos are stored (by default)

.SH "REPORTING BUGS"
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
.SH "SEE ALSO"
\fBgnunet\-pseudonym\fP(1), \fBgnunet\-gns\fP(1)
