.Dd June 5, 2018
.Dt GNUNET-TIMEOUT 1
.Os
.Sh NAME
.Nm gnunet-timeout
.Nd
run process with timeout
.Sh SYNOPSIS
.Nm
.Ao Ar duration Ac
.Ao Ar command Ac
.Ao args ... Ac
.Sh DESCRIPTION
.Nm
can be used to run another process with a timeout.
It is provided because the standard "timout" utility may not be available on all platforms.
.Sh SEE ALSO
.Xr timeout 1
.sp
The full documentation for gnunet is maintained as a Texinfo manual.
If the
.Xr info 1
and gnunet programs are properly installed at your site, the command
.Pp
.Dl info gnunet
.Pp
should give you access to the complete handbook,
.Pp
.Dl info gnunet-c-tutorial
.Pp
will give you access to a tutorial for developers.
.sp
Depending on your installation, this information is also available in
.Xr gnunet 7 and
.Xr gnunet-c-tutorial 7 .
.\".Sh HISTORY
.\".Sh AUTHORS
.Sh BUGS
Report bugs by using
.Lk https://bugs.gnunet.org
or by sending electronic mail to
.Aq Mt gnunet-developers@gnu.org .
