.\" This file is part of GNUnet.
.\" Copyright (C) 2001-2019 GNUnet e.V.
.\"
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3 or
.\" any later version published by the Free Software Foundation; with no
.\" Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
.\" copy of the license is included in the file
.\" FDL-1.3.
.\"
.\" A copy of the license is also available from the Free Software
.\" Foundation Web site at http://www.gnu.org/licenses/fdl.html}.
.\"
.\" Alternately, this document is also available under the General
.\" Public License, version 3 or later, as published by the Free Software
.\" Foundation.  A copy of the license is included in the file
.\" GPL3.
.\"
.\" A copy of the license is also available from the Free Software
.\" Foundation Web site at http://www.gnu.org/licenses/gpl.html
.\"
.\" SPDX-License-Identifier: GPL3.0-or-later OR FDL1.3-or-later
.\"
.Dd March 6, 2019
.Dt GNUNET-NSE 1
.Os
.Sh NAME
.Nm gnunet-nse
.Nd show network size estimates from NSE service
.Sh SYNOPSIS
.Nm
.Op Fl c Ar FILENAME | Fl -config= Ns Ar FILENAME
.Op Fl h | -help
.Op Fl L Ar LOGLEVEL | Fl -loglevel= Ns Ar LOGLEVEL
.Op Fl l Ar LOGFILE | Fl -logfile= Ns Ar LOGFILE
.Op Fl v | -version
.Sh DESCRIPTION
.Nm
is a command line tool to show network size estimates from
the NSE service of GNUnet.
.Bl -tag -width indent
.It Fl c Ar FILENAME | Fl -config= Ns Ar FILENAME
Use the configuration file FILENAME.
.It Fl h | -help
Print short help on options.
.It Fl L Ar LOGLEVEL | Fl -loglevel= Ns Ar LOGLEVEL
Use LOGLEVEL for logging.
Valid values are DEBUG, INFO, WARNING and ERROR.
.It Fl l Ar LOGFILE | Fl -logfile= Ns Ar LOGFILE
Configure logging to write logs to LOGFILE.
.It Fl v | -version
Print GNUnet version number.
.El
.Sh FILES
.Pa gnunet.conf
Configuration file for gnunet.
.Sh SEE ALSO
.Xr gnunet.conf 5
.sp
The full documentation for gnunet is maintained as a Texinfo manual.
If the
.Xr info 1
gnunet programs are properly installed at your site, the command
.Bd -literal -offset indent -compact
        info gnunet
.Ed
should give you access to the complete handbook,
.Bd -literal -offset indent -compact
        info gnunet-c-tutorial
.Ed
will give you access to a tutorial for developers.
.Pp
Depending on your installation, this information is also
available in
.Xr gnunet 7 and
.Xr gnunet-c-tutorial 7 .
.Sh HISTORY
This man page first appeared in GNUnet 0.11.1.
.Sh AUTHORS
This page was originally written by
.An Bertrand Marc Aq Mt bmarc@debian.org
for Debian's gnunet package (man page date: 2014).
Further edits and conversion to mdoc were done by
.An ng0 Aq Mt ng0@gnunet.org .
.Sh BUGS
Report bugs by using
.Lk https://bugs.gnunet.org
or by sending electronic mail to
.Aq Mt bug-gnunet@gnu.org .
