.TH GNUNET\-DNS2GNS 1 "Jan 4, 2012" "GNUnet"

.SH NAME
gnunet\-dns2gns \- display information about transport resource allocation

.SH SYNOPSIS
.B gnunet\-dns2gns
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-dns2gns\fP can be used to 

.SH OPTIONS
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.


.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <bug\-gnunet@gnu.org>

.SH SEE ALSO
gnunet\-transport(1)
