.TH GNUNET\-NAMESTORE 1 "Mar 5, 2012" "GNUnet"

.SH NAME
gnunet\-namestore \- manipulate GNUnet zones

.SH SYNOPSIS
.B gnunet\-namestore
.RI [ options ] -z ZONEFILE
.br

.SH DESCRIPTION
\fBgnunet\-namestore\fP can be used to create and manipulate a GNS zone.  

.SH OPTIONS
.B
.IP "\-a, \-\-add"
Desired operation is adding a record
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-d, \-\-delete"
Desired operation is deleting a record
.B
.IP "\-D, \-\-display"
Desired operation is listing of matching records
.B
.IP "\-e TIME, \-\-expiration=TIME"
Specifies expiration time of record to add; format is relative time, i.e "1 h" or "7 d 30 m".  Supported units are "ms", "s", "min" or "minutes", "h" (hours), "d" (days) and "a" (years).
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-n NAME, \-\-name=NAME"
Name of the record to add/delete/display
.B
.IP "\-t TYPE, \-\-type=TYPE"
Type of the record to add/delete/display (i.e. "A", "AAAA", "NS", "PKEY", "MX" etc.)
.B
.IP "\-v, \-\-version"
Print GNUnet version number.
.B
.IP "\-V VALUE, \-\-value=VALUE"
Value to store or remove from the GNS zone.  Specific format depends on the record type.  A records expect a dotted decimal IPv4 address, AAAA records an IPv6 address, PKEY a public key in GNUnet's printable format, and CNAME and NS records should be a domain name.
.B
.IP "\-z FILENAME, \-\-zonekey=FILENAME"
Specifies the filename with the private key for the zone (mandatory option)


.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>


.SH "SEE ALSO"
\fBgnunet\-gns\fP(1)
