#!/sbin/openrc-run
# Contributor: xrs <xrs@mail36.net>
# Maintainer: xrs <xrs@mail36.net>

name="gnunet-system-service"
description="A secure and privacy enhancing peer-to-peer overlay network"
command="/usr/lib/gnunet/libexec/gnunet-service-arm"
command_args="-c /etc/gnunet.conf"
command_user="gnunet:gnunet"
command_background="yes"
pidfile="/run/${SVCNAME}.pid"

depend() {
	need net
	before gnunet-user-services
}
