# Script that generates syntax tree and launches SeaSpider for creating GNUnet expression database
JTB_COMMAND=$(../../../bin/jtb .)
JAVACC_COMMAND=$(../../../bin/javacc .)

$(JTB_COMMAND)
$(JAVACC_COMMAND)
 